services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=12346
      - POSTGRES_USER=root
      - POSTGRES_DB=movie_catalog

  redis:
    image: redis
    command: redis-server
    ports:
      - 6379:6379
    depends_on:
      - db
